apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-param
spec:
  params:
    - name: who
      type: string
  steps:
    - name: hello-with-parametre
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - /bin/bash
        - -c
        - echo "Hello $(params.who)"

# $ tkn task start hello-param --showlog -p who=Muhsin