apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: multiple-steps
spec:
  steps:
    - name: first
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - /bin/bash
        - -c
        - echo "First step running"
    - name: second
      image: alpine
      command:
        - /bin/bash
        - -c
        - echo "Second step running"

# $ kubectl apply –f ./multiple.yaml
# $ tkn task ls
# $ tkn task start multiple-steps
# $ tkn task start multiple-steps --showlog

# bash script çalıştırılabilir.
# parametreler verilebilir.
