apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: script
spec:
  steps:
    - name: step-with-script
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/usr/bin/env bash
        echo "Installing necessary tooling"
        dnf install iputils -y
        ping tubitak.gov.tr -c 5
        echo "All done!"

# $ kubectl apply –f ./script.yaml
# $ tkn task ls
# $ tkn task start step-with-script
# $ tkn task start step-with-script --showlog
