apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-auth
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN SSH PRIVATE KEY-----
    B3BlbnNzaC...
    NhAAAA...
    -----END SSH PRIVATE KEY-----