apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-and-list
spec:
  params:
    - name: repo
      type: string
      description: Git repository to be cloned
      default: https://github.com/muhsin09/func
  workspaces:
    - name: source
  steps:
    - name: clone
      image: alpine/git
      workingDir: $(workspaces.source.path)
      command:
        - /bin/sh
      args:
        - -c
        - git clone -v $(params.repo) ./source
    - name: list
      image: alpine
      workingDir: $(workspaces.source.path)/source
      command:
        - /bin/sh
      args:
        - -c
        - ls ./source

# $ kubectl apply -f workspaces/clone-ls.yaml
# $ tkn task start clone-and-list -w name=source,emptyDir="" --showlog

---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-tr-
spec:
  workspaces:
    - name: source
      emptyDir: { }
  taskRef:
    name: clone-and-list